// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/flpnascto/clean-architecture-go/internal/entity"
	"github.com/flpnascto/clean-architecture-go/internal/event"
	"github.com/flpnascto/clean-architecture-go/internal/infra/database"
	"github.com/flpnascto/clean-architecture-go/internal/infra/web"
	"github.com/flpnascto/clean-architecture-go/internal/usecase"
	"github.com/flpnascto/clean-architecture-go/pkg/events"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func ListOrdersUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.ListOrdersUseCaseType {
	orderRepository := database.NewOrderRepository(db)
	listOrders := event.NewListOrders()
	listOrdersUseCaseType := usecase.ListOrdersUseCase(orderRepository, listOrders, eventDispatcher)
	return listOrdersUseCaseType
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	listOrders := event.NewListOrders()
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderCreated, listOrders)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, event.NewListOrders, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventInterface), new(*event.ListOrders)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))

var setListOrdersEvent = wire.NewSet(event.NewListOrders, wire.Bind(new(events.EventInterface), new(*event.ListOrders)))

var setWebOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(web.OrderCreatedEventInterface), new(*event.OrderCreated)))

var setWebListOrdersEvent = wire.NewSet(event.NewListOrders, wire.Bind(new(web.ListOrdersEventInterface), new(*event.ListOrders)))
